# Generated by Django 5.1 on 2024-08-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_no', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=255)),
                ('design_type', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('quality', models.CharField(max_length=100)),
                ('shuttle_or_mat', models.CharField(max_length=100)),
                ('receiving', models.DateField()),
            ],
        ),
    ]
