# Generated by Django 5.1 on 2024-08-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='receiving',
            field=models.CharField(max_length=100),
        ),
    ]
