# Generated by Django 5.1 on 2024-08-26 14:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_product_receiving'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='challan_no',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='design_type',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='receiving',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='remarks',
            field=models.TextField(blank=True, default='-', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='shuttle_or_mat',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
