# Generated by Django 5.1 on 2024-08-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_product_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='design_type',
            new_name='design',
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
