# Generated by Django 5.1 on 2024-08-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_product_form_enum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('loomNo', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('design_type', models.CharField(max_length=100)),
                ('warp', models.CharField(max_length=100)),
                ('warpColor', models.CharField(max_length=100)),
                ('weft', models.CharField(max_length=100)),
                ('weftColor', models.CharField(max_length=100)),
                ('widthInch', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lengthMeter', models.DecimalField(decimal_places=2, max_digits=7)),
                ('threadCount', models.IntegerField()),
                ('reed', models.CharField(max_length=100)),
                ('bOrM', models.CharField(max_length=50)),
                ('dentThread', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
