# Generated by Django 5.1 on 2024-08-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_loom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loom',
            old_name='design_type',
            new_name='design',
        ),
        migrations.AddField(
            model_name='loom',
            name='type',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='loom',
            name='lengthMeter',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='loom',
            name='widthInch',
            field=models.IntegerField(),
        ),
    ]
